# Generated by Django 5.1.3 on 2024-11-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
